# Generated by Django 5.2.8 on 2026-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
